// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Events.EFModel.Models;

public partial class Person
{
    public int Id { get; set; }

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string FirstNameTranscription { get; set; } = null!;

    public string LastNameTranscription { get; set; } = null!;

    public string AddressLine { get; set; } = null!;

    public string PostalCode { get; set; } = null!;

    public string City { get; set; } = null!;

    public string AddressCountry { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string ContactPhone { get; set; } = null!;

    public DateOnly BirthDate { get; set; }

    public string DocumentNumber { get; set; } = null!;

    public string CountryCode { get; set; } = null!;

    public virtual Country CountryCodeNavigation { get; set; } = null!;

    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();
}