// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Events.WebAPI.Handlers.EF.Models;

public partial class Country
{
    public string Code { get; set; } = null!;

    public string Alpha3 { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string? Translations { get; set; }

    public virtual ICollection<Person> People { get; set; } = new List<Person>();
}