// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Events.WebAPI.Handlers.EF.Models;

public partial class Event
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public DateOnly EventDate { get; set; }

    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();
}