// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Events.WebAPI.Handlers.EF.Models;

public partial class Registration
{
    public int Id { get; set; }

    public int PersonId { get; set; }

    public int SportId { get; set; }

    public int EventId { get; set; }

    public DateTime RegisteredAt { get; set; }

    public virtual Event Event { get; set; } = null!;

    public virtual Person Person { get; set; } = null!;

    public virtual Sport Sport { get; set; } = null!;
}